name: tgt
version: 1.0.0
profile: duckdb
model-paths:
- models
macro-paths:
- macros
clean-targets:
- target
- dbt_packages
vars:
  target_schema: fallback_schema
  source_table: aadsc_ftd_participant
models:
  tgt:
    +materialized: table
    tgt_condition: null
    tgt_participant: null
