#!/bin/bash

# Define your PostgreSQL connection parameters
DB_HOST=""
DB_USER=""
DB_NAME=""


# Insert the SQL generated by process_data.py.
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "{Output sql from process data}")
    FROM '{filepath}'
    DELIMITER ',' 
    CSV HEADER;
    ;"
